USE tecnica;

CREATE TABLE SUBDIRECCION (
    ID_SUBDIRECCION INT AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_SUBDIRECCION),
    UNIQUE (NOMBRE)
);

CREATE TABLE EMPLEADO (
    ID_EMPLEADO INT AUTO_INCREMENT,
    NOMBRES VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    DPI VARCHAR(20) NOT NULL,
    NIT VARCHAR(20),
    FECHA_NACIMIENTO DATE NOT NULL,
    FECHA_INGRESO DATE NOT NULL,
    CORREO VARCHAR(150),
    TELEFONO VARCHAR(20),
    DIRECCION VARCHAR(255),
    ACTIVO BOOLEAN NOT NULL DEFAULT TRUE,
    FECHA_BAJA DATE NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_EMPLEADO),
    UNIQUE (DPI),
    UNIQUE (CORREO)
);

CREATE TABLE PUESTO (
    ID_PUESTO INT AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255),
    NIVEL VARCHAR(50),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_PUESTO),
    UNIQUE (NOMBRE)
);

CREATE TABLE TIPO_CONTRATO (
    ID_TIPO_CONTRATO INT AUTO_INCREMENT,
    NOMBRE VARCHAR(80) NOT NULL,
    DESCRIPCION VARCHAR(255),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_TIPO_CONTRATO),
    UNIQUE (NOMBRE)
);

CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO INT AUTO_INCREMENT,
    ID_SUBDIRECCION INT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255),
    ID_JEFE INT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_DEPARTAMENTO),
    UNIQUE (NOMBRE),
    CONSTRAINT FK_DEPARTAMENTO_SUBDIRECCION
        FOREIGN KEY (ID_SUBDIRECCION)
        REFERENCES SUBDIRECCION(ID_SUBDIRECCION),
    CONSTRAINT FK_DEPARTAMENTO_JEFE
        FOREIGN KEY (ID_JEFE)
        REFERENCES EMPLEADO(ID_EMPLEADO)
);

CREATE TABLE UNIDAD_FUNCIONAL (
    ID_UNIDAD_FUNCIONAL INT AUTO_INCREMENT,
    ID_DEPARTAMENTO INT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_UNIDAD_FUNCIONAL),
    CONSTRAINT FK_UNIDADFUNCIONAL_DEPARTAMENTO
        FOREIGN KEY (ID_DEPARTAMENTO)
        REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO)
);

CREATE TABLE UNIDAD_OPERATIVA (
    ID_UNIDAD_OPERATIVA INT AUTO_INCREMENT,
    ID_UNIDAD_FUNCIONAL INT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_UNIDAD_OPERATIVA),
    CONSTRAINT FK_UNIDADOPERATIVA_UNIDADFUNCIONAL
        FOREIGN KEY (ID_UNIDAD_FUNCIONAL)
        REFERENCES UNIDAD_FUNCIONAL(ID_UNIDAD_FUNCIONAL)
);

CREATE TABLE CONTRATO (
    ID_CONTRATO INT AUTO_INCREMENT,
    ID_EMPLEADO INT NOT NULL,
    ID_TIPO_CONTRATO INT NOT NULL,
    NUMERO_CONTRATO VARCHAR(50) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NULL,
    OBSERVACIONES VARCHAR(500),
    ACTIVO BOOLEAN NOT NULL DEFAULT TRUE,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_CONTRATO),
    UNIQUE (NUMERO_CONTRATO),
    CONSTRAINT FK_CONTRATO_EMPLEADO
        FOREIGN KEY (ID_EMPLEADO)
        REFERENCES EMPLEADO(ID_EMPLEADO),
    CONSTRAINT FK_CONTRATO_TIPO_CONTRATO
        FOREIGN KEY (ID_TIPO_CONTRATO)
        REFERENCES TIPO_CONTRATO(ID_TIPO_CONTRATO)
);

CREATE TABLE HISTORIAL_PUESTOS (
    ID_HISTORIAL_PUESTO INT AUTO_INCREMENT,
    ID_EMPLEADO INT NOT NULL,
    ID_PUESTO INT NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NULL,
    MOTIVO VARCHAR(255),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_HISTORIAL_PUESTO),
    CONSTRAINT FK_HISTPUESTO_EMPLEADO
        FOREIGN KEY (ID_EMPLEADO)
        REFERENCES EMPLEADO(ID_EMPLEADO),
    CONSTRAINT FK_HISTPUESTO_PUESTO
        FOREIGN KEY (ID_PUESTO)
        REFERENCES PUESTO(ID_PUESTO),
    INDEX IDX_HISTPUESTO_EMPLEADO_VIGENTE (ID_EMPLEADO, FECHA_FIN)
);

CREATE TABLE HISTORIAL_DEPARTAMENTOS (
    ID_HISTORIAL_DEPARTAMENTO INT AUTO_INCREMENT,
    ID_EMPLEADO INT NOT NULL,
    ID_UNIDAD_OPERATIVA INT NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NULL,
    MOTIVO VARCHAR(255),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_HISTORIAL_DEPARTAMENTO),
    CONSTRAINT FK_HISTDEPTO_EMPLEADO
        FOREIGN KEY (ID_EMPLEADO)
        REFERENCES EMPLEADO(ID_EMPLEADO),
    CONSTRAINT FK_HISTDEPTO_UNIDADOPERATIVA
        FOREIGN KEY (ID_UNIDAD_OPERATIVA)
        REFERENCES UNIDAD_OPERATIVA(ID_UNIDAD_OPERATIVA),
    INDEX IDX_HISTDEPTO_EMPLEADO_VIGENTE (ID_EMPLEADO, FECHA_FIN)
);

CREATE TABLE HISTORIAL_SALARIOS (
    ID_HISTORIAL_SALARIO INT AUTO_INCREMENT,
    ID_EMPLEADO INT NOT NULL,
    SALARIO DECIMAL(10,2) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NULL,
    MOTIVO VARCHAR(255),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_HISTORIAL_SALARIO),
    CONSTRAINT FK_HISTSALARIO_EMPLEADO
        FOREIGN KEY (ID_EMPLEADO)
        REFERENCES EMPLEADO(ID_EMPLEADO),
    CONSTRAINT CK_HISTSALARIO_POSITIVO
        CHECK (SALARIO > 0),
    INDEX IDX_HISTSALARIO_EMPLEADO_VIGENTE (ID_EMPLEADO, FECHA_FIN)
);

CREATE TABLE BITACORA_AUDITORIA (
    ID_BITACORA BIGINT AUTO_INCREMENT,
    TABLA_AFECTADA VARCHAR(64) NOT NULL,
    ID_REGISTRO_AFECTADO INT NOT NULL,
    OPERACION ENUM('INSERT','UPDATE','DELETE') NOT NULL,
    USUARIO VARCHAR(100) NOT NULL,
    FECHA_OPERACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VALORES_ANTERIORES JSON NULL,
    VALORES_NUEVOS JSON NULL,
    PRIMARY KEY (ID_BITACORA),
    INDEX IDX_BITACORA_TABLA_REGISTRO (TABLA_AFECTADA, ID_REGISTRO_AFECTADO),
    INDEX IDX_BITACORA_FECHA (FECHA_OPERACION)
);

CREATE VIEW VW_EMPLEADO_PUESTO_ACTUAL AS
SELECT hp.ID_EMPLEADO, hp.ID_PUESTO, hp.FECHA_INICIO
FROM HISTORIAL_PUESTOS hp
WHERE hp.FECHA_FIN IS NULL;

CREATE VIEW VW_EMPLEADO_DEPARTAMENTO_ACTUAL AS
SELECT hd.ID_EMPLEADO, hd.ID_UNIDAD_OPERATIVA, hd.FECHA_INICIO
FROM HISTORIAL_DEPARTAMENTOS hd
WHERE hd.FECHA_FIN IS NULL;

CREATE VIEW VW_EMPLEADO_SALARIO_ACTUAL AS
SELECT hs.ID_EMPLEADO, hs.SALARIO, hs.FECHA_INICIO
FROM HISTORIAL_SALARIOS hs
WHERE hs.FECHA_FIN IS NULL;

DELIMITER $$

CREATE TRIGGER TRG_HISTPUESTO_CERRAR_VIGENTE
BEFORE INSERT ON HISTORIAL_PUESTOS
FOR EACH ROW
BEGIN
    IF NEW.FECHA_FIN IS NULL THEN
        UPDATE HISTORIAL_PUESTOS
           SET FECHA_FIN = DATE_SUB(NEW.FECHA_INICIO, INTERVAL 1 DAY)
         WHERE ID_EMPLEADO = NEW.ID_EMPLEADO
           AND FECHA_FIN IS NULL;
    END IF;
END$$

CREATE TRIGGER TRG_HISTDEPTO_CERRAR_VIGENTE
BEFORE INSERT ON HISTORIAL_DEPARTAMENTOS
FOR EACH ROW
BEGIN
    IF NEW.FECHA_FIN IS NULL THEN
        UPDATE HISTORIAL_DEPARTAMENTOS
           SET FECHA_FIN = DATE_SUB(NEW.FECHA_INICIO, INTERVAL 1 DAY)
         WHERE ID_EMPLEADO = NEW.ID_EMPLEADO
           AND FECHA_FIN IS NULL;
    END IF;
END$$

CREATE TRIGGER TRG_HISTSALARIO_CERRAR_VIGENTE
BEFORE INSERT ON HISTORIAL_SALARIOS
FOR EACH ROW
BEGIN
    IF NEW.FECHA_FIN IS NULL THEN
        UPDATE HISTORIAL_SALARIOS
           SET FECHA_FIN = DATE_SUB(NEW.FECHA_INICIO, INTERVAL 1 DAY)
         WHERE ID_EMPLEADO = NEW.ID_EMPLEADO
           AND FECHA_FIN IS NULL;
    END IF;
END$$

DELIMITER ;