DROP TRIGGER IF EXISTS TRG_EMPLEADO_AI;
DROP TRIGGER IF EXISTS TRG_EMPLEADO_AU;
DROP TRIGGER IF EXISTS TRG_EMPLEADO_AD;

CREATE TRIGGER TRG_EMPLEADO_AI
AFTER INSERT ON EMPLEADO
FOR EACH ROW
INSERT INTO BITACORA_AUDITORIA (
    TABLA_AFECTADA,
    ID_REGISTRO_AFECTADO,
    OPERACION,
    USUARIO,
    VALORES_ANTERIORES,
    VALORES_NUEVOS
)
VALUES (
    'EMPLEADO',
    NEW.ID_EMPLEADO,
    'INSERT',
    COALESCE(NULLIF(@usuario_app, ''), CURRENT_USER()),
    NULL,
    JSON_OBJECT(
        'ID_EMPLEADO', NEW.ID_EMPLEADO,
        'NOMBRES', NEW.NOMBRES,
        'APELLIDOS', NEW.APELLIDOS,
        'DPI', NEW.DPI,
        'NIT', NEW.NIT,
        'FECHA_NACIMIENTO', NEW.FECHA_NACIMIENTO,
        'FECHA_INGRESO', NEW.FECHA_INGRESO,
        'CORREO', NEW.CORREO,
        'TELEFONO', NEW.TELEFONO,
        'DIRECCION', NEW.DIRECCION,
        'ACTIVO', NEW.ACTIVO,
        'FECHA_BAJA', NEW.FECHA_BAJA
    )
);

CREATE TRIGGER TRG_EMPLEADO_AU
AFTER UPDATE ON EMPLEADO
FOR EACH ROW
INSERT INTO BITACORA_AUDITORIA (
    TABLA_AFECTADA,
    ID_REGISTRO_AFECTADO,
    OPERACION,
    USUARIO,
    VALORES_ANTERIORES,
    VALORES_NUEVOS
)
VALUES (
    'EMPLEADO',
    NEW.ID_EMPLEADO,
    'UPDATE',
    COALESCE(NULLIF(@usuario_app, ''), CURRENT_USER()),
    JSON_OBJECT(
        'ID_EMPLEADO', OLD.ID_EMPLEADO,
        'NOMBRES', OLD.NOMBRES,
        'APELLIDOS', OLD.APELLIDOS,
        'DPI', OLD.DPI,
        'NIT', OLD.NIT,
        'FECHA_NACIMIENTO', OLD.FECHA_NACIMIENTO,
        'FECHA_INGRESO', OLD.FECHA_INGRESO,
        'CORREO', OLD.CORREO,
        'TELEFONO', OLD.TELEFONO,
        'DIRECCION', OLD.DIRECCION,
        'ACTIVO', OLD.ACTIVO,
        'FECHA_BAJA', OLD.FECHA_BAJA
    ),
    JSON_OBJECT(
        'ID_EMPLEADO', NEW.ID_EMPLEADO,
        'NOMBRES', NEW.NOMBRES,
        'APELLIDOS', NEW.APELLIDOS,
        'DPI', NEW.DPI,
        'NIT', NEW.NIT,
        'FECHA_NACIMIENTO', NEW.FECHA_NACIMIENTO,
        'FECHA_INGRESO', NEW.FECHA_INGRESO,
        'CORREO', NEW.CORREO,
        'TELEFONO', NEW.TELEFONO,
        'DIRECCION', NEW.DIRECCION,
        'ACTIVO', NEW.ACTIVO,
        'FECHA_BAJA', NEW.FECHA_BAJA
    )
);

CREATE TRIGGER TRG_EMPLEADO_AD
AFTER DELETE ON EMPLEADO
FOR EACH ROW
INSERT INTO BITACORA_AUDITORIA (
    TABLA_AFECTADA,
    ID_REGISTRO_AFECTADO,
    OPERACION,
    USUARIO,
    VALORES_ANTERIORES,
    VALORES_NUEVOS
)
VALUES (
    'EMPLEADO',
    OLD.ID_EMPLEADO,
    'DELETE',
    COALESCE(NULLIF(@usuario_app, ''), CURRENT_USER()),
    JSON_OBJECT(
        'ID_EMPLEADO', OLD.ID_EMPLEADO,
        'NOMBRES', OLD.NOMBRES,
        'APELLIDOS', OLD.APELLIDOS,
        'DPI', OLD.DPI,
        'NIT', OLD.NIT,
        'FECHA_NACIMIENTO', OLD.FECHA_NACIMIENTO,
        'FECHA_INGRESO', OLD.FECHA_INGRESO,
        'CORREO', OLD.CORREO,
        'TELEFONO', OLD.TELEFONO,
        'DIRECCION', OLD.DIRECCION,
        'ACTIVO', OLD.ACTIVO,
        'FECHA_BAJA', OLD.FECHA_BAJA
    ),
    NULL
);
